import { cn } from '@/lib/utils';
import './globals.css';
import type { Metadata } from 'next';
import { VT323 } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Providers from '@/components/Providers';

const inter = VT323({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'zedquiz',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'antialiased min-h-screen pt-16')}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
